### ISSUE TITLE
Issue with of Evision.drawcontour function

### ISSUE THREAD

**Issue by navrkr** [cocoa-xu/evision#105]
**Feel free to ping me on telegram[@navrkr] or twitter[@navrkr]  (need to have private chat regarding this project)**

Please refer to the following syntax error and fix it asap please.
![Screenshot from 2022-10-11 12-54-47](https://user-images.githubusercontent.com/68466584/195023249-d312b436-fb26-40bf-8afd-3f2ccb01acd1.png)

**Comment by kipcole9** [comment]
@navrkr you don't have the right to say "fix it ASAP please".  You have the right to do the hard work and make a contribution if this is important to you.  In addition please check your facts: this is not a syntax error. It is a dialyzer warning. And at this point in the development cycle I don't believe @cocoa-xu is focused on producing dialyzer-clean code.

**Comment by navrkr** [comment]
Ping me on twitter or telegram i would like to contribute.

**Comment by kipcole9** [comment]
No needs to use alternative channels, that's what the issue tracker is for.

**Comment by navrkr** [comment]
Sorry for saying ASAP, the thing is "i solved a problem in python
completely" but I want it to implement in elixir, i find docs confusing but
fine in its initial release. I am new to elixir too 🫣. So I need some
guidance and help to complete my project in time.

**Comment by navrkr** [comment]
> @navrkr you don't have the right to say "fix it ASAP please". You have the right to do the hard work and make a contribution if this is important to you. In addition please check your facts: this is not a syntax error. It is a dialyzer warning. And at this point in the development cycle I don't believe @cocoa-xu is focused on producing dialyzer-clean code.

And also it is returning nil so Its a mandatory thing not just dialyzer-clear.

**Comment by cocoa-xu** [comment]
Hi @navrkr, the inline docs can be pulled up by typing `h Evision.drawContours` in iex. This is a builtin feature of iex.

Also, there is a nice-looking HTML version available on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), and the one you're looking for can be found here [https://hexdocs.pm/evision/Evision.html#drawContours/5](https://hexdocs.pm/evision/Evision.html#drawContours/5).

If you are looking for the documentation of other functions, you can search the function name in the top-left search box on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), or type `h Evision.functionName` (or `h Evision.SubModule.functionName`) in iex.

For example, to search for the usage of `Evision.drawContours/{4,5}` on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), please type `drawContours` in the top-left search box and press the enter (windows) / return (macOS) key. The resulting list will show on the right side once you begin typing anything in the search box. Then you can click on it (or the one you want) in the list on the right side, and it will bring you to the corresponding section.

For all keyword arguments, they should be passed to the function like this:
```elixir
Evision.function(
  positional_argument_1,
  positional_argument_2,
  name_of_first_keyword_argument: value_of_first_keyword_argument,
  name_of_the_second_keyword_argument: value_of_the_second_keyword_argument
)
```

For `Evision.drawContours/5`, it **could** be
```elixir
Evision.drawContours(
  image,
  index,
  [0, 255, 255],
  thickness: -1,
  lineType: 0,
  hierarchy: hierarchy_info,
  maxLevel: 1,
)
```

Also, you don't need to pass a value for each keyword argument.
```elixir
Evision.drawContours(
  image,
  index,
  [0, 255, 255],
  thickness: -1,
  lineType: 0,
  maxLevel: 1,
)
```

**Comment by cocoa-xu** [comment]
> need to have private chat regarding this project

Sorry, I don't offer direct support for private projects.

**Comment by navrkr** [comment]
Thanks a ton, so sweet of you for taking time and explaining everything ☺️, I already had look at docs and it's great and helpful in a great way.🤟

> Hi @navrkr, the inline docs can be pulled up by typing `h Evision.drawContours` in iex. This is a builtin feature of iex.
> 
> Also, there is a nice-looking HTML version available on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), and the one you're looking for can be found here https://hexdocs.pm/evision/Evision.html#drawContours/5.
> 
> If you are looking for the documentation of other functions, you can search the function name in the top-left search box on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), or type `h Evision.functionName` (or `h Evision.SubModule.functionName`) in iex.
> 
> For example, to search for the usage of `Evision.drawContours/{4,5}` on [https://hexdocs.pm/evision/](https://hexdocs.pm/evision/Evision.html), please type `drawContours` in the top-left search box and press the enter (windows) / return (macOS) key. The resulting list will show on the right side once you begin typing anything in the search box. Then you can click on it (or the one you want) in the list on the right side, and it will bring you to the corresponding section.
> 
> For all keyword arguments, they should be passed to the function like this:
> 
> ```elixir
> Evision.function(
>   positional_argument_1,
>   positional_argument_2,
>   name_of_first_keyword_argument: value_of_first_keyword_argument,
>   name_of_the_second_keyword_argument: value_of_the_second_keyword_argument
> )
> ```
> 
> For `Evision.drawContours/5`, it **could** be
> 
> ```elixir
> Evision.drawContours(
>   image,
>   index,
>   [0, 255, 255],
>   thickness: -1,
>   lineType: 0,
>   hierarchy: hierarchy_info,
>   maxLevel: 1,
> )
> ```
> 
> Also, you don't need to pass a value for each keyword argument.
> 
> ```elixir
> Evision.drawContours(
>   image,
>   index,
>   [0, 255, 255],
>   thickness: -1,
>   lineType: 0,
>   maxLevel: 1,
> )
> ```

**Comment by navrkr** [comment]
> > need to have private chat regarding this project
> 
> Sorry, I don't offer direct support for private projects.

No issues thanks for your support, i can manage to do it on my own as I already figured out how to do it on python!

**Comment by cocoa-xu** [comment]
> the thing is "i solved a problem in python completely" but I want it to implement in elixir

**Comment by cocoa-xu** [comment]
> the thing is "i solved a problem in python completely" but I want it to implement in elixir

Some (language) features available in Python are not in Elixir, and it's the same the other way around. It's hard to copy the code from one language and expect it to work in another language.

**Comment by cocoa-xu** [comment]
> Please refer to the following syntax error and fix it asap please.

For this one, I've managed to generate function specs in PR #101. It's not released yet because I need some time to check if the generated specs are correct or not.

**Comment by cocoa-xu** [comment]
> No issues thanks for your support, i can manage to do it on my own as I already figured out how to do it on python!

Producing dialyzer-clean code is on my list but there are other things that I have to solve first.

As the main issue here has been solved, I'll close this issue for now.
