### ISSUE TITLE
doubt on image croping in elixir 

### ISSUE THREAD

**Issue by Jagan3534** [cocoa-xu/evision#106]
i haven doubt in `Nx.slice` we are working on it we converted image to 2d array by using your instructions could you please help us @navrkr @cocoa-xu 
![ans](https://user-images.githubusercontent.com/95116414/195003242-afce82f7-62e2-4fb6-8203-d4c263c1fdda.png)

how can slice function work on it 

![2](https://user-images.githubusercontent.com/95116414/195003403-966a7806-2309-4861-96b2-8232cf6dc9d5.png)

we are trying to give all but its not work please help us sir

_Originally posted by @Jagan3534 in https://github.com/cocoa-xu/evision/issues/102#issuecomment-1274102267_

**Comment by kipcole9** [comment]
Once you have converted the image to an `Nx.Tensor.t/0` you are no longer working in code related to `eVision`, you are working in `Nx`. So the question you ask is not relevant to `eVision` at all. If there is an issue (and I am not familiar for Nx enough to guide you) then you should open an issue on the `Nx` repository. If you question is more usage related, the you should post a question in the [Elixir Forum](https://elixirforum.com).

**Comment by Jagan3534** [comment]
> hen you should open an issue on the `Nx`

thank you sir
