### ISSUE TITLE
 doubt on image croping in Evision.Nx and Nx.slice

### ISSUE THREAD

**Issue by Jagan3534** [cocoa-xu/evision#107]
i haven doubt in `Nx.slice` we are working on it we converted image to 2d array by using your instructions could you please help us @navrkr @cocoa-xu 
![ans](https://user-images.githubusercontent.com/95116414/195003242-afce82f7-62e2-4fb6-8203-d4c263c1fdda.png)

how can slice function work on it 

![2](https://user-images.githubusercontent.com/95116414/195003403-966a7806-2309-4861-96b2-8232cf6dc9d5.png)

we are trying to give all but its not work please help us sir

_Originally posted by @Jagan3534 in https://github.com/cocoa-xu/evision/issues/102#issuecomment-1274102267_

**Comment by cocoa-xu** [comment]
Hi @Jagan3534, the inline docs can be pulled up by typing `h Nx.slice` in iex. 

Also, there is a nice-looking HTML version available on [https://hexdocs.pm/nx/](https://hexdocs.pm/nx/Nx.html), and the one you're looking for can be found here [https://hexdocs.pm/nx/Nx.html#slice/4](https://hexdocs.pm/nx/Nx.html#slice/4).

If you are looking for the usage/examples of other `Nx` functions, you can search the function name in the top-left search box on [https://hexdocs.pm/nx/](https://hexdocs.pm/nx/Nx.html). 

For example, to search for the usage of `Nx.slice` on [https://hexdocs.pm/nx/](https://hexdocs.pm/nx/Nx.html), please type `slice` in the top-left search box and press the enter (windows) / return (macOS) key. The resulting list will show on the right side, and you can click on it (or the one you want), which will bring you to the corresponding section.

Then please read the documentation and examples. If their documentation or examples are not clear, you can either raise an issue on [elixir-nx/nx](https://github.com/elixir-nx/nx) asking them for more details. Or perhaps you can implement the function you'd like to use, or improve the existing function(s) (and their documentation/examples) and open a PR on [elixir-nx/nx](https://github.com/elixir-nx/nx).

**Comment by Jagan3534** [comment]
thank you sir we got the it sir
