### ISSUE TITLE
small doubt regarding contours in evision 

### ISSUE THREAD

**Issue by Jagan3534** [cocoa-xu/evision#114]
i get the values of `findContours` after getting is their any method to seperate `contours` using in built function like in python `imutil.grabcontours`

the code is here 
```
`def grab_contours(cnts):
    # if the length the contours tuple returned by cv2.findContours
    # is 2 then we are using either OpenCV v2.4, v4-beta, or
    # v4-official
    if len(cnts) == 2:
        cnts = cnts[0]

    # if the length of the contours tuple is 3 then we are using
    # either OpenCV v3, v4-pre, or v4-alpha
    elif len(cnts) == 3:
        cnts = cnts[1]

    # otherwise OpenCV has changed their cv2.findContours return
    # signature yet again and I have no idea WTH is going on
    else:
        raise Exception(("Contours tuple must have length 2 or 3, "
            "otherwise OpenCV changed their cv2.findContours return "
            "signature yet again. Refer to OpenCV's documentation "
            "in that case"))

    # return the actual contours array
    return cnts`
```
could please help us sir @cocoa-xu @josevalim

**Comment by cocoa-xu** [comment]
1. search keywords: `elixir how to get the first element of a list`

    The first result in Google: [List — Elixir v1.12.3 - HexDocs](https://hexdocs.pm/elixir/1.12/List.html). Scroll down, and we have

    > ### Summary
    > ...
    > [first(list, default \\ nil)](https://hexdocs.pm/elixir/1.12/List.html#first/2)
    >    Returns the first element in list or default if list is empty.

    Wow, there is a function that would do exactly what I want!

2. Okay, let's try it.
    
    ```elixir
    iex> cnts = Evision.findContours(........)
    iex> List.first(cnts)
    ** (FunctionClauseError) no function clause matching in List.first/2
       ...
    ```

    IT DOES NOT WORK! ~~PLEASE FIX IT AS SOON AS POSSIBLE!~~ Why? Maybe there is a tiny teeny chance that `cnts` is not a list.

3. search keywords: `elixir how to check if a variable is a list`

    The first result in Google: [How do you check for the type of variable in Elixir - stackoverflow.com](https://stackoverflow.com/questions/28377135/how-do-you-check-for-the-type-of-variable-in-elixir)

    The answer with the highest score:
    
    > Starting in elixir 1.2 there is an i command in iex that will list the type and more of any Elixir variable.
    >
    > ```iex> foo = "a string" 
    > iex> i foo 
    > Term
    >  "a string"
    > Data type
    >  BitString
    > Byte size
    >  8
    > Description
    >  This is a string: a UTF-8 encoded binary. It's printed surrounded by
    >  "double quotes" because all UTF-8 encoded codepoints in it are        printable.
    > Raw representation
    >   <<97, 32, 115, 116, 114, 105, 110, 103>>
    > Reference modules
    >   String, :binary
    > ```

4. Looks like we can check the variable type by typing `i var_name`. Let's try it.

    ```elixir
    iex> cnts = Evision.findContours(........)
    iex> i cnts
    Term
      ...
    Data type
      Tuple
    Reference modules
      Tuple
    Implemented protocols
      IEx.Info, Inspect, Kino.Render, Nx.Container
    ```

    Wow, I could never know that it was a tuple. But...!

7. search keywords: `elixir how to take the first element of a tuple`

    The first result in Google: [Tuple — Elixir v1.12.3 - HexDocs](https://hexdocs.pm/elixir/1.12/Tuple.html). Let read the docs for another minute, just read it for a minute.

    > Functions for working with tuples.
    >
    > Please note the following functions for tuples are found in [Kernel](https://hexdocs.pm/elixir/1.12/Kernel.html):
    > 
    > - [elem/2](https://hexdocs.pm/elixir/1.12/Kernel.html#elem/2) - accesses a tuple by index
    > - [put_elem/3](https://hexdocs.pm/elixir/1.12/Kernel.html#put_elem/3) - inserts a value into a tuple by index
    > - [tuple_size/1](https://hexdocs.pm/elixir/1.12/Kernel.html#tuple_size/1) - gets the number of elements in a tuple

    Wow! `elem/2 - accesses a tuple by index`! That sounds like what we want! Let's try it.

8. elem/2

    ```elixir
    iex> cnts = Evision.findContours(........)
    iex> elem(cnts, 0)
    [
      %Evision.Mat{
        channels: 2,
        dims: 2,
        type: {:s, 32},
        raw_type: 12,
        shape: {786, 1, 2},
        ref: #Reference<0.2031396339.107610132.64185>
      },
      ...
    ]
    ```

    Impossible! Unbelievable! Incredible! I just separated `contours` using built-in functions.

Hey bro, I never knew that people even write documentation for their code and have search engines available these days, because I would never bother to read or do a simple search. Why do they pay so much effort into something that I would never use lol?

**Comment by cocoa-xu** [comment]
Please use the [ElixirForum](http://www.elixirforum.com/) for questions/help/feedback, where a wider community will be able to help you. Thank you!

**Comment by Jagan3534** [comment]
sorry sir i think my question is not understand clear sir 
already i divided using `{con,hei} = contours` in shell 
i gave input like this but in color it getting error i check in evision but the example code in github its not working sir
`OpenCV.drawContours(img,key,-1,(0,255,0),-1)`
but my doubt is like in drawContour its getting an error like  
![image](https://user-images.githubusercontent.com/95116414/196054593-abcacd60-5e73-41f9-b2ae-77984f9a45d4.png)

**Comment by cocoa-xu** [comment]
1. because `color` should be a tuple, like `(0,255,0)` is a tuple in python, `{0,255,0}` is the corresponding tuple in elixir
2. the fifth argument is wrong

**Comment by cocoa-xu** [comment]
> 2. the fifth argument

I **guess** you want to specify **thickness**, so:

```elixir
Evision.drawContours(src, contours, index, {0, 0, 255}, thickness: 2)
```

The example works, I tested it again. And a minimal one.

```elixir
import Bitwise

# Load image in color
src = Evision.imread("pca_test.jpg")

# Load image in grayscale
gray = Evision.imread("pca_test.jpg", flags: Cv.cv_IMREAD_GRAYSCALE())

# binarization
{_, bw} = Evision.threshold(gray, 50, 255, Cv.cv_THRESH_BINARY() ||| Cv.cv_THRESH_OTSU())

# Find all the contours in the thresholded image
{contours, _} = Evision.findContours(bw, Cv.cv_RETR_LIST(), Cv.cv_CHAIN_APPROX_NONE())

contours =
  contours
  # Calculate the area of each contour
  |> Enum.map(&{Evision.contourArea(&1), &1})
  # Ignore contours that are too small or too large
  |> Enum.reject(fn {area, _c} -> area < 100 or area > 100_000 end)
contours = Enum.map(contours, &elem(&1, 1))

# Draw each contour
src =
  for index <- 0..(Enum.count(contours) - 1), reduce: src do
    src ->
      Evision.drawContours(src, contours, index, {0, 0, 255}, thickness: 2)
  end
```

**Comment by Jagan3534** [comment]
thanks a lot sir

**Comment by creddyravindra** [comment]
hello sir, we have done it in python, how to we use `sorted(contours, key=cv2.contourArea, reverse=True)[:15]` in elixir, is there any built in function to seperate edges in evision

```contours = sorted(contours, key=cv2.contourArea, reverse=True)[:15]
location = None
# Finds rectangular contour
for contour in contours:
  approx = cv2.approxPolyDP(contour, 15, True)
  if len(approx) == 4:
    location = approx
    break```

**Comment by kipcole9** [comment]
This issue tracker is for reporting bugs. Please use [Elixir Forum](https://elixirforum.com) for help requests.  And why are you calling Cocoa "sir"?

**Comment by Jagan3534** [comment]
Bro please don't ask my questions bro sir  said to use forums bro please follow that bro
