### ISSUE TITLE
sorry for what is did . we have a small problem in sort sir

### ISSUE THREAD

**Issue by Jagan3534** [cocoa-xu/evision#115]
I apologise if i sound rude, i did not know english that well may be this is why i sounds rude.

here same we got the error in the elixir in python we wrote like this
in elixir we tried to give but in sort 2 nd parameter is doubted sir in Evision `hexdoxs` we tried to see the example but in new version they  dont show 
`contours = sorted(contours, key=cv2.contourArea, reverse=True)`

could you please help us

**Comment by cocoa-xu** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) for questions/help/feedback, where a wider community will be able to help you. Thank you!

**Comment by Jagan3534** [comment]
sorry sir in `ElixirForum` already some one is posted sir but they didn't get any responds sir

**Comment by kipcole9** [comment]
Please stop opening issues that are not bug reports. You have been asked to use [Elixir Forum](https://elixirforum.com) for discussion on how to use Elixir or Elixir libraries.  Github issues are for bug reports.

You also continue to use "sir" when if you had the courtesy to even consider the author of this library you would not address her that way.

**Comment by kipcole9** [comment]
If you haven't had a response then perhaps consider how you asked the question. Its a wonderful community, but you are asking people to prioritise your questions over their own work.  Make it easy for people to want to help. Show what work you have done *in Elixir*. Describe your issue *in Elixir* and the issues you face.

There are several of you working on the same problem and at this point none of you are showing much respect for the people you are asking to do work for you.

**Comment by kipcole9** [comment]
No response in Elixir Forum is *not* an excuse to keep opening issues. The author is well in her right to just close them without comment.

**Comment by Jagan3534** [comment]
thank you sorry for inconvenience
