### ISSUE TITLE
Proposal: Function grouping by ex_doc because too many functions in the OpenCV module to read and search

### ISSUE THREAD

**Issue by zacky1972** [cocoa-xu/evision#12]
When opening docs of `evision`, I found too many functions in the `OpenCV` module to read and search.

So, I propose grouping functions by the following `ex_doc` features:

http://f.cybrox.eu/exdocdemo/Mix.Tasks.Docs.html#module-groups

**Comment by cocoa-xu** [comment]
Oh, I didn't know that before! Thanks for sharing the link, and I'll try to modify `gen2.py` to take advantage of this feature.

**Comment by cocoa-xu** [comment]
e85a003 should make it easier to read and search now (as shown in the screenshot below).

<img width="1218" alt="Screenshot 2022-01-08 at 16 01 57" src="https://user-images.githubusercontent.com/89497197/148651151-bf23dd74-4aae-4588-bfbc-e97c898f751a.png">

**Comment by cocoa-xu** [comment]
I'll close this issue for now, but please feel free to reopen it if finer groups are desired. 🚀
