### ISSUE TITLE
[Feature | Livebook] Make the default preview for Evision.Mat  "Image" instead of "Raw"

### ISSUE THREAD

**Issue by tusqasi** [cocoa-xu/evision#124]
It maybe better to keep the default output to "Image" instead of "Raw". 
An alternative could be to save the last type of preview selected.
Even better some way to change the preview type. Like a setting.

It is annoying to switch to image each time I run the cell

![image](https://user-images.githubusercontent.com/24749908/198899140-1a657100-65ff-4e6d-8ae7-08bde90a7bab.png)

Some previous discussion
https://github.com/livebook-dev/livebook/discussions/1506

**Comment by cocoa-xu** [comment]
> Even better some way to change the preview type. Like a setting.

Implemented this feature in 0.1.16 (PR #126). Also, it is available on hex.pm now.
