### ISSUE TITLE
Segmentation fault at Evision.DNN.TextDetectionModelDB.setBinaryThreshold /2

### ISSUE THREAD

**Issue by thehaigo** [cocoa-xu/evision#136]
I tried TextDetection. but OpenCV was segmentation fault 

below code
```exliir
alias Evision, as: Ev
image = "text.jpg" |> Ev.imread
weights = "DB_IC15_resnet50.onnx"
model = 
  Ev.DNN.TextDetectionModelDB.textDetectionModelDB(weights)
  |> Ev.DNN.TextDetectionModelDB.setInputParams(
    scale: 1.0 / 255.0,
    size: {736, 1280},
    mean: {122.67891434, 116.66876762, 104.00698793},
    swapRB: false,
    crop: false
  )
  |> Ev.DNN.TextDetectionModelDB.setBinaryThreshold(0.3)
  |> Ev.DNN.TextDetectionModelDB.setPolygonThreshold(0.5)
  |> Ev.DNN.TextDetectionModelDB.setMaxCandidates(200)
  |> Ev.DNN.TextDetectionModelDB.setUnclipRatio(2.0)

{vertices, confidences} = Ev.DNN.TextDetectionModelDB.detect(model, image)
```
setInputParams passed 
setBinaryThreshold rise below
```
Segmentation fault: 11
```
model zip is here https://gihyo.jp/assets/files/book/2022/978-4-297-12775-6/download/7.6.zip

**Comment by cocoa-xu** [comment]
Hi @thehaigo thank you for providing the information! I'll look into this today ;)

**Comment by cocoa-xu** [comment]
This issue is fixed in v0.1.21, but I cannot run the release GitHub Action because GitHub is experiencing some issues at the moment. I'll let you know once I can build v0.1.21 with GitHub Action.

<img width="1028" alt="Screenshot 2022-11-25 at 15 08 48" src="https://user-images.githubusercontent.com/89497197/204013246-76d7f620-4717-4458-a30a-854c53a2f389.png">

**Comment by cocoa-xu** [comment]
v0.1.21 is on hex now :)

**Comment by thehaigo** [comment]
work and success! 
thank you!
![スクリーンショット 2022-11-26 23 50 03](https://user-images.githubusercontent.com/91950/204094930-e19b5f9a-dfd2-4d16-9203-b221a258180c.png)
