### ISSUE TITLE
[smartcell] added smart cells for models in opencv_zoo

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#141]
Link to [opencv_zoo](https://github.com/opencv/opencv_zoo).

Expected UI:

<img width="927" alt="Screenshot 2022-12-12 at 00 08 32" src="https://user-images.githubusercontent.com/89497197/206937324-a858a754-a931-4785-b8d1-6bb150d2c575.png">

Tasks:

- [x] [Face Detection] [YuNet](https://github.com/opencv/opencv_zoo/blob/master/models/face_detection_yunet)
- [x] [Face Recognition] [SFace](https://github.com/opencv/opencv_zoo/blob/master/models/face_recognition_sface)
- [x] [Text Detection] [DB-IC15](https://github.com/opencv/opencv_zoo/blob/master/models/text_detection_db)
- [x] [Text Detection] [DB-TD500](https://github.com/opencv/opencv_zoo/blob/master/models/text_detection_db)
- [x] [Text Recognition] [CRNN-EN](https://github.com/opencv/opencv_zoo/blob/master/models/text_recognition_crnn)
- [x] [Text Recognition] [CRNN-CN](https://github.com/opencv/opencv_zoo/blob/master/models/text_recognition_crnn)
- [x] [Image Classification] [PP-ResNet](https://github.com/opencv/opencv_zoo/blob/master/models/image_classification_ppresnet)
- [x] [Image Classification] [MobileNet-V1](https://github.com/opencv/opencv_zoo/blob/master/models/image_classification_mobilenet)
- [x] [Human Segmentation] [PP-HumanSeg](https://github.com/opencv/opencv_zoo/blob/master/models/human_segmentation_pphumanseg)

Helper functions:
- [x] Download models to a (perhaps global) cache directory. `Evision.Zoo.download(url, filename, cache_dir)`

Skipped:
- [Object Tracking] [DaSiamRPN](https://github.com/opencv/opencv_zoo/blob/master/models/object_tracking_dasiamrpn)
- [Image Classification] [MobileNet-V2](https://github.com/opencv/opencv_zoo/blob/master/models/image_classification_mobilenet)
- [Hand Pose Estimation] [MP-HandPose](https://github.com/opencv/opencv_zoo/blob/master/models/handpose_estimation_mediapipe)
- [Person Re-Identification] [YoutuReID](https://github.com/opencv/opencv_zoo/blob/master/models/person_reid_youtureid)
- [Palm Detection] [MP-PalmDet](https://github.com/opencv/opencv_zoo/blob/master/models/palm_detection_mediapipe)

**Comment by cocoa-xu** [comment]
MobileNet-V2 failed to load, see [opencv/opencv #21698](https://github.com/opencv/opencv/issues/21698)

**Comment by cocoa-xu** [comment]
[DaSiamRPN](https://github.com/opencv/opencv_zoo/blob/master/models/object_tracking_dasiamrpn) will require video stream. Put off for now.

**Comment by cocoa-xu** [comment]
[MP-HandPose](https://github.com/opencv/opencv_zoo/blob/master/models/handpose_estimation_mediapipe)'s example code in opencv_zoo does not seem to work. Put off for now.

**Comment by cocoa-xu** [comment]
[YoutuReID](https://github.com/opencv/opencv_zoo/blob/master/models/person_reid_youtureid) involves multiple images as the gallery and at least one image as the query. Since kino does not support uploading multiple images yet (in a convenient way), this will not be implemented for now.

**Comment by Wigny** [comment]
It's planned to implement the [License Plate Detection with YuNet](https://github.com/opencv/opencv_zoo/tree/master/models/license_plate_detection_yunet) at some point?

**Comment by cocoa-xu** [comment]
> It's planned to implement the [License Plate Detection with YuNet](https://github.com/opencv/opencv_zoo/tree/master/models/license_plate_detection_yunet) at some point?

Hi @Wigny, yes, I can add it maybe in the next version (v0.1.26 or v0.1.27), but that model was only trained with Chinese license plates. Therefore, as stated in its introduction, "the detection results of other license plates with this model may be limited".

So I'm considering adding some text inputs so that users can load their own license plate detection models.

**Comment by Wigny** [comment]
Loading o custom license plate detection model would be amazing! Looking forward for it...
