### ISSUE TITLE
OpenCV stitching seems to not work

### ISSUE THREAD

**Issue by lawik** [cocoa-xu/evision#15]
Love this effort, just gave it a whirl [on stream](https://t.co/woGdsJcuOJ) and had lots of fun.

I tried to create a stitcher and both `OpenCV.Sticher.create()` and `OpenCV.stitcher_create()` would just return the below error in an error tuple:

```
 'OpenCV(4.5.4) /home/lawik/projects/eyes/deps/evision/3rd_party/opencv/opencv-4.5.4/modules/stitching/src/stitcher.cpp:94: error: (-5:Bad argument) Invalid stitching mode. Must be one of Stitcher::Mode in function \'create\'\n'}
```

I couldn't find a way of passing a mode and the docs seemed to indicate it mostly wants a boolean. I don't know, I may be missing something but in case this identifies a useful issue with evision I figured I'd mention it.

**Comment by cocoa-xu** [comment]
Hi, thank you for trying this library! (Also, I checked the stream, that was a great one!)

I can confirm this was a bug when handling one or more `enum` type arguments that appeared in the function call, for [example](https://github.com/opencv/opencv/blob/4.5.4/modules/stitching/include/opencv2/stitching.hpp#L184).

```cpp
CV_WRAP static Ptr<Stitcher> create(Mode mode = Stitcher::PANORAMA);
```

d28b1d5 should fix this issue (and other similar cases) by
- declaring their types as their underlying types in the generated code. `std::underlying_type_t<Mode> mode = ...`
- static casting them back to the original type when using them. `static_cast<Mode>(...)`

**Comment by lawik** [comment]
Sounds great!

I was amazed at what worked. Hope the stream did your work some level of justice.

Let me know if you have some examples you think I should try. I have a decent chunk of Nerves devices and media gear.

**Comment by cocoa-xu** [comment]
Haha, to be honest, I was surprised that a number of functions just worked as we would expect! 

I wonder if it is possible for me to use some of your code as examples here? Or, if you would like to create a PR please feel free to do so!

One more thing, in my test run, I observed that the return value was something like `{:ok, {:ok, 0}, #Reference}` , where the `0` was one of the values in the [`Status`](https://github.com/opencv/opencv/blob/4.5.4/modules/stitching/include/opencv2/stitching.hpp#L152) enum in C++.

a099f2a fixed the return value to what it was supposed to be (the correct result should be something like `{:ok, 0, #Reference}`).

**Comment by lawik** [comment]
Sweet.

Use whatever you like from the stuff I did in the stream :)

Very curious to see if the stitching stuff works well.

Want to find a good example of improving photos as well. That camera is pretty crappy.

I don't know if haar cascades are still a relevant way for  finding faces but I'd want some kind of face tracking. That I can actually do extra neat things with. ML isn't my space so now idea where the best bang for the buck is today.

**Comment by cocoa-xu** [comment]
The API works as expected now, and here is [an example](https://github.com/cocoa-xu/evision/blob/main/examples/stitching.livemd). I'm gonna close this issue, but feel free to reopen it if there are any glitches. :)
