### ISSUE TITLE
[CI-macOS only] DNN module tests constantly cause segmentation faults on CI and cannot be reproduced locally

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#153]
This issue tracks the problem that DNN module tests constantly cause segmentation faults in macOS on GitHub Actions. These segmentation faults are observed after bumping the OpenCV version to 4.7.0. These crashes didn't appear when re-running a previous workflow (using OpenCV 4.6.0).

I also tested the [macOS x86_64 binaries](https://github.com/cocoa-xu/evision/actions/runs/3862365533) built on GitHub CI on my Intel MacBook Pro (which has an 8th Gen Intel 8950HK CPU) 30 times, and not a single time I observed any segmentation faults.

The peak memory usage was around 1.5GB. According to [GitHub's docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), their macOS runner has 14 GB of RAM, so it wasn't an OOM issue. 

However, since I cannot reproduce this issue locally, it could be something related to the macOS GitHub CI. 

A final thought for this: it could be that some AVX2 instructions were not supported on the macOS runner's CPU. I'll do a final test with these SIMD CPU features/instructions disabled.

**Comment by cocoa-xu** [comment]
It seems that the issue has been reported, https://github.com/opencv/opencv/issues/23080

**Comment by cocoa-xu** [comment]
No segmentation faults after disabling Winograd. https://github.com/cocoa-xu/evision/actions/runs/3863248117/jobs/6585317659

**Comment by zihaomu** [comment]
Hi @cocoa-xu, Are there any reproducible models that I can test?

**Comment by cocoa-xu** [comment]
Hi @zihaomu, yep, I was testing a few models. Sorry that the testing code was written in Elixir, but they all follow the standard way of using the OpenCV dnn module.

1. The first one is the YOLOv4 model.
  - [yolov4.cfg](https://github.com/cocoa-xu/evision/blob/main/test/testdata/yolov4.cfg)
  - [yolov4.weights](https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov4.weights)
  - [test code](https://github.com/cocoa-xu/evision/blob/main/test/dnn_detection_model_test.exs)

2. Text detection DB model.
  - [DB_IC15_resnet18.onnx](https://github.com/cocoa-xu/evision-extra/raw/main/testdata/text-detection/DB_IC15_resnet18.onnx)
  - [test code](https://github.com/cocoa-xu/evision/blob/main/test/dnn_text_detection_model_db_test.exs)

3. Text detection EAST model.
  - [EAST.pb](https://www.dropbox.com/s/r2ingd0l3zt8hxs/frozen_east_text_detection.tar.gz?dl=1)
  - [test code](https://github.com/cocoa-xu/evision/blob/main/test/dnn_text_detection_model_east_test.exs)

**Comment by cocoa-xu** [comment]
In a previous GitHub workflow, they [passed](https://github.com/cocoa-xu/evision/actions/runs/3864117262/jobs/6586721380#step:13:1) if Winograd is disabled, and they [all failed](https://github.com/cocoa-xu/evision/actions/runs/3864117262/jobs/6586721380#step:14:1) when having Winograd enabled.

**Comment by zihaomu** [comment]
Hi @cocoa-xu, can you please try this branch in your CI to check if this patch can handle the segmentation fault? https://github.com/opencv/opencv/pull/23112

**Comment by cocoa-xu** [comment]
Sure, I'll set up one!

**Comment by cocoa-xu** [comment]
No luck, they still crash using https://github.com/opencv/opencv/pull/23112; 
workflow log: https://github.com/cocoa-xu/evision/actions/runs/3867633124/jobs/6592540953#step:14:32

```
export ENABLE_WINOGRAD=yes
Excluding tags: [dnn: false, ml: false, photo: false, video: false]
Including tags: [:require_downloading, :require_ffmpeg]

[ INFO:0@0.431] global registry_parallel.impl.hpp:96 ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
/Users/runner/work/_temp/b4f6c02d-67c5-4964-a298-7bbfdff91bd4.sh: line 2: 31504 Segmentation fault: 11  mix test --include require_downloading --include require_ffmpeg test/dnn_detection_model_test.exs
Excluding tags: [dnn: false, ml: false, photo: false, video: false]
Including tags: [:require_downloading, :require_ffmpeg]

[ INFO:0@0.227] global tf_importer.cpp:3014 populateNet DNN/TF: parsing model (N/A version info). Number of nodes = 7975
[ INFO:0@0.227] global tf_importer.cpp:30[21](https://github.com/cocoa-xu/evision/actions/runs/3867633124/jobs/6592540953#step:14:22) populateNet DNN/TF: parsing config (N/A version info). Number of nodes = 256
[ INFO:1@2.255] global registry_parallel.impl.hpp:96 ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
/Users/runner/work/_temp/b4f6c02d-67c5-4964-a[29](https://github.com/cocoa-xu/evision/actions/runs/3867633124/jobs/6592540953#step:14:30)8-7bbfdff91bd4.sh: line 3: [31](https://github.com/cocoa-xu/evision/actions/runs/3867633124/jobs/6592540953#step:14:32)582 Segmentation fault: 11  mix test --include require_downloading --include require_ffmpeg test/dnn_detection_test.exs
```

**Comment by cocoa-xu** [comment]
<img width="1920" alt="Screenshot 2023-01-08 at 15 30 57" src="https://user-images.githubusercontent.com/89497197/211205059-53cca242-638e-48b7-83bc-54504bf03851.png">

Hi @zihaomu, I'm not sure but if you want, it's possible to ssh to the runner and run the test in lldb using the following command; please find the shell [here](https://github.com/cocoa-xu/evision/actions/runs/3867633124/jobs/6592540953#step:15:39); 

```bash
export COMMANDS="$(ELIXIR_CLI_DRY_RUN=1 mix)"
export CMD_ARGS="${COMMANDS:3}"
export ERL="$(which erl)"
export ERL_BASE="$(dirname $(dirname ${ERL}))"
export ERLEXEC="$(find "${ERL_BASE}" -name erlexec)"
export BINDIR="$(dirname ${ERLEXEC})"
export START_BOOT="$(find $ERL_BASE -name start.boot | grep -v release)"
export ROOTDIR="$(dirname $(dirname ${START_BOOT}))"
export EMU=beam

lldb -- ${ERLEXEC} -pa /usr/local/Cellar/elixir/1.14.2/bin/../lib/eex/ebin /usr/local/Cellar/elixir/1.14.2/bin/../lib/elixir/ebin /usr/local/Cellar/elixir/1.14.2/bin/../lib/ex_unit/ebin /usr/local/Cellar/elixir/1.14.2/bin/../lib/iex/ebin /usr/local/Cellar/elixir/1.14.2/bin/../lib/logger/ebin /usr/local/Cellar/elixir/1.14.2/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra /usr/local/bin/mix test --include require_downloading --include require_ffmpeg test/dnn_detection_model_test.exs
```

**Comment by zihaomu** [comment]
Thanks for your work and suggestion, I will keep working on it.

**Comment by cocoa-xu** [comment]
> Thanks for your work and suggestion, I will keep working on it.

Thank you very much! :)

Also, please let me know if you intend to use the ssh session, if yes, I'll keep it running; or I'll close it in a few minutes just in case of unwanted users on the Internet.

**Comment by zihaomu** [comment]
Thank you for your kindness, I'm more familiar with the local IDE for debugging.

**Comment by zihaomu** [comment]
Hi @cocoa-xu, I just got your point. In your CI, the `CV_TRY_AVX2` is true, but `checkHardwareSupport(CPU_AVX2)` is false. This is quite wired for me because it means you don't get the speedup of AVX2 instructions when inferring the model.

And I just update the patch (We just disable the Winograd branch when this inconsistency occurs), and this time everything should work well.

BTW, I don't understand why the return value of `checkHardwareSupport(CPU_AVX2)` is false on your CI, maybe it is another issue.

**Comment by cocoa-xu** [comment]
Hi @zihaomu, the CPU in the macOS runner sometimes would be an Intel E3 1650 v2 or an Intel E5-2697 v2, both of which only support AVX but not AVX2. 

OpenCV will compile AVX2 routes on x86_64 macOS so that the precompiled binaries can use AVX2 instructions whenever `checkHardwareSupport(CPU_AVX2)` returns `true`. So we really should detect the CPU features (AVX2 or SIMD128) on-the-fly.

**Comment by zihaomu** [comment]
Hi @cocoa-xu, thanks for your details. 
I think the `CV_TRY_AVX2` will be set to true when CPU supports AVX or AVX2, while `checkHardwareSupport(CPU_AVX2)` is only true for AVX2.

> So we really should detect the CPU features (AVX2 or SIMD128) on-the-fly.

In short term, we will disable Winograd when AVX2 was not supported on X86, like the PR I submitted.
And in long term, I will support Winograd with AVX. It may take about two weeks. After that, we can get speed up based on AVX.
