### ISSUE TITLE
[Proposal] Add Access behaviour to Evision.VideoCapture.t

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#155]
I believe it would be useful to be able to reference video frames as `video[0]` or `video[0..200]` or `video[0..-1]`.  There could also be a variant which is `video[[0..10, :millisecond]]` and `video[[0..10, :frame]]`.

If you think this is a reasonable idea I am happy to submit a PR.

**Comment by cocoa-xu** [comment]
Hi @kipcole9, I think this is a good feature of videos, but the source of `Evision.VideoCapture` (`cv::VideoCapture`) can also be a camera. So the subscription/Access behaviour doesn't really make sense if the input source is a camera. 

I'm not quite sure if there are any APIs we can use to tell the difference, but if you can find one, then this feature can be made available for video files. :)

**Comment by kipcole9** [comment]
It’s a good point about the camera.  My observation is that camera devices return “frame_count” equal to 0.0.Do you think that is a good and reliable indicator?Sent from my iPhoneOn 8 Jan 2023, at 15:47, Cocoa ***@***.***> wrote:﻿
Hi @kipcole9, I think this is a good feature of videos, but the source of Evision.VideoCapture (cv::VideoCapture) can also be a camera. So the subscription/Access behaviour doesn't really make sense if the input source is a camera.
I'm not quite sure if there are any APIs we can use to tell the difference, but if you can find one, then this feature can be made available for video files. :)

**Comment by cocoa-xu** [comment]
I checked OpenCV's docs, and this approach should be okay (although this is not a documented use). There are also some keys that only have non-negative values if the source is a camera, like `CAP_PROP_CONTRAST` and `CAP_PROP_SATURATION`. So maybe it would be better to use `CAP_PROP_CONTRAST` and/or `CAP_PROP_SATURATION`?

**Comment by kipcole9** [comment]
Given the challenges around reliably seeking to a frame I think this is not a good idea.  I have implemented `Image.Video.stream!/2` that probably fits most use cases that Access might otherwise cover.
