### ISSUE TITLE
Accuracy of Evision.VideoCapture.t frame count?

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#156]
I notice that the frame count returned in the `Evision.VideoCapture.t` struct isn't the same as that reported by `ffmpeg`. When enumerating the frames in the video, the count of images/frames returned is the same as that reported by ffmeg.  Its possible the intent is for the frame count to be an estimate (ie doc update only required) but it may also be a bug.

### Evision.VideoCapture frame count
Evision reports frame count as `173.0` but when streaming each frame the count
is actually 171.
```elixir
# The test file is at https://github.com/kipcole9/image/blob/main/test/support/video/video_sample.mp4
iex> Evision.VideoCapture.videoCapture("./test/support/video/video_sample.mp4")
%Evision.VideoCapture{
  fps: 30.0,
  frame_count: 173.0,
  frame_width: 1920.0,
  frame_height: 1080.0,
  isOpened: true,
  ref: #Reference<0.2884281812.3844210708.170269>
}

# Code in the Image lib master that streams frames
iex> Enum.to_list(Image.Video.stream!("./test/support/video/video_sample.mp4")) |> Enum.count()
171
```
### ffmpeg frame count
When asking ffmpeg how many frames it returns 171 (same as the streaming code, different to that reported by `Evision.VideoCapture.t`.
```bash
% ffprobe -v error -select_streams v:0 -count_frames \
    -show_entries stream=nb_read_frames -of csv=p=0 ./test/support/video/video_sample.mp4
171
```

**Comment by cocoa-xu** [comment]
Yes, I think this is a decision from the upstream code, and this number is meant to be somewhat of an estimated number. Related link: https://stackoverflow.com/a/47796468

**Comment by cocoa-xu** [comment]
And similar issues have been reported at OpenCV's repo, https://github.com/opencv/opencv/issues/16821, https://github.com/opencv/opencv/issues/19924, https://github.com/opencv/opencv/issues/19930

**Comment by kipcole9** [comment]
Cool, that's what I suspected.  I will note that the frame count is an estimate in `Image.Video.open/1`.  Feel free to close if you think this isn't going to be resolved upstream.

**Comment by cocoa-xu** [comment]
> Feel free to close if you think this isn't going to be resolved upstream.

Yep, I'm afraid that this issue has to be addressed in OpenCV's codebase. The related code in evision only extracts this number and puts it into the map.

```cpp
    keys[item_index] = enif_make_atom(env, "frame_count");
    values[item_index] = enif_make_double(env, cap->get(cv::CAP_PROP_FRAME_COUNT));
    item_index++;
```

https://github.com/cocoa-xu/evision/blob/main/c_src/modules/evision_video_api.h#L31

**Comment by cocoa-xu** [comment]
Okay, after some inspections, there is nothing much I can do in evision to address this issue, and it entirely depends on the upstream.

**Comment by kipcole9** [comment]
Turns out the FFMPEG backend does report the correct frame count. I will add some notes to `Image.Video.image_from_video/2` to that effect.

**Comment by cocoa-xu** [comment]
> Turns out the FFMPEG backend does report the correct frame count.

Yes, but it creates an external dependency, and I don't really want to enable it in the precompiled library. At least, not yet...

**Comment by kipcole9** [comment]
Completely agree with you on that!  It was just an interesting observation and something I can add to my documentation.

**Comment by cocoa-xu** [comment]
Yep, also one more thing to note here, while it's possible to compile a lite version of FFMPEG, I think most of the users who need it would expect a "full" version. besides that, including FFMPEG libraries by default can create some license issues for some users.
