### ISSUE TITLE
NIF error returned from Evision.VideoIORegistry.getBackendName/1

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#158]
When looking to identify the configured VideoCapture backends it seems there is a documentation mismatch or API error in `Evision.VideoIORegistry.getBackendName/1`.  

The spec for `Evision.VideoIORegistry.getBackendName/1` reads:
```elixir
@spec getBackendName([number()]) :: binary() | {:error, String.t()}
```
So I expected that passing the output of `Evision.VideoIORegistry.getBackends/0` would be acceptable. I also tried a single backend number like `[1900]` with the same error result:
```elixir
iex> Evision.VideoIORegistry.getBackends
[1900, 1800, 2300, 1200, 2000, 2200, 2500]
iex> Evision.VideoIORegistry.getBackends() |> Evision.VideoIORegistry.getBackendName()
** (ArgumentError) argument error
    (evision 0.1.25) :evision_nif.videoio_registry_getBackendName([api: [1900, 1800, 2300, 1200, 2000, 2200, 2500]])
    (evision 0.1.25) lib/generated/evision_videoioregistry.ex:56: Evision.VideoIORegistry.getBackendName/1
    iex:11: (file)
```

**Comment by cocoa-xu** [comment]
I'll check `Evision.VideoIORegistry` related functions. `getBackendName` and `hasBackend` shouldn't be expecting a list as their input.

**Comment by kipcole9** [comment]
I did try with a single integer argument with a different error result:
```elixir
iex> Evision.VideoCapture.getBackendName 1900
{:error,
 "cannot get `Ptr<cv::VideoCapture>` from `self`: mismatched type or invalid resource?"}
```

**Comment by cocoa-xu** [comment]
`Evision.VideoCapture.getBackendName` returns the backend name that is currently used by an `Evision.VideoCapture` instance. It's an instance method so you need to pass in an `Evision.VideoCapture.t()`
