### ISSUE TITLE
Error running gen2.py

### ISSUE THREAD

**Issue by stefkohub** [cocoa-xu/evision#16]
Hi,
I am trying to compile this module on Nvidia Jetson Nano.
The compilation cannot correctly finish since the gen2.py script is complaining with the error:

<class '_ast.Num'> not implemented yet

Can you help me in understanding what I can do to fix it? If needed, I can provide the full output of mix deps.compile.

Thank you.

**Comment by cocoa-xu** [comment]
Hi, thanks for the reporting!

I tested the script on Python3.8 and it seems that the Python version on your Nvidia Jetson Nano is before 3.8. I'll try to install an earlier version of Python and test the `gen2.py` script again. For a quick workaround, you can replace the [lines here](https://github.com/cocoa-xu/evision/blob/main/py_src/gen2.py#L1048) with the following.

```
            import sys
            if sys.version_info.minor < 8:
                if type(node) is ast.Num:
                    self.expression = f'{node.value}'
                else:
                    print(type(node), "not implemented yet")
                    sys.exit(1)
            else:
                print(type(node), "not implemented yet")
                sys.exit(1)
```

**Comment by stefkohub** [comment]
Hi @cocoa-xu thank you for you reply!
You're right, the Python version on my Nano is 3.6. I applied the changes that you've suggested but I had to modify node.value to node.n.
Now I've been able ti compile it, thank you! :)

**Comment by cocoa-xu** [comment]
0dae8af should fix this issue! 🎉  Please feel free to reopen if the issue persists.
