### ISSUE TITLE
Evision.VideoCapture.set/3 type inconsistent with retval

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#167]
Tested on Evision `0.1.26-rc.2`:

The type signature for `Evision.VideoCapture.set/3` is:
```elixir
@spec set(t(), integer(), number()) :: t() | {:error, String.t()}
```
However the `retval` is actually `boolean() | {:error, String.t()}`.  The `@doc` also notes the return code is a boolean.

**Comment by cocoa-xu** [comment]
Hi @kipcole9, thanks for reporting this issue! I'll look into it and fix it in the next version. :)
