### ISSUE TITLE
`Evision.Zoo.TextRecognition.CRNN.init/2` failing to download charset

### ISSUE THREAD

**Issue by Wigny** [cocoa-xu/evision#179]
Since https://github.com/opencv/opencv_zoo/pull/123/ removed the charset files from the `text_recognition_crnn` folder, the [charset_info/1](https://github.com/cocoa-xu/evision/blob/v0.1.28/lib/zoo/text_recognition/crnn.ex#L291) function is returning the URL for non-existing files.

**Comment by cocoa-xu** [comment]
Hi @Wigny, thanks for reporting this issue! Since they embedded charset into the source file, I might do that as well. I'll push a new commit soon!
