### ISSUE TITLE
Text recognition failing in the latest versions

### ISSUE THREAD

**Issue by Wigny** [cocoa-xu/evision#185]
In the latest versions of the library, basically it is able to detect text but not to recognize it.

When running the v0.1.25:
<img src="https://user-images.githubusercontent.com/23202981/227388125-d7e93a49-0040-4e65-873a-ea2f3a47bf90.png" width="500px" />

But when running the v0.1.29:
<img src="https://user-images.githubusercontent.com/23202981/227388178-283017dd-6b10-40cc-ba6d-8fbf8e75ae9a.png" width="500px" />

Has any configuration changed since the v0.1.25 I'm not aware of?

> [failing_text_recognition.livemd](https://github.com/cocoa-xu/evision/files/11057254/failing_text_recognition.md)
[working_text_recognition.livemd](https://github.com/cocoa-xu/evision/files/11057255/working_text_recognition.md)
[sample.jpg](https://arturshams.files.wordpress.com/2015/07/sample1.jpg)

**Comment by Wigny** [comment]
If you found problems running the working example (v0.1.25) because of https://github.com/cocoa-xu/evision/issues/179, please, download the charset before testing: 
```bash
wget https://raw.githubusercontent.com/opencv/opencv_zoo/933a4171e3dfa2f67b4078602c76f91ac6a5299a/models/text_recognition_crnn/charset_3944_CN.txt -O ~/.cache/text_recognition_CRNN_CN_2021nov_charset_3944_CN.txt
```

**Comment by cocoa-xu** [comment]
v0.1.30 is out.

**Comment by Wigny** [comment]
Hey, thank you for the time and effort you spend on this amazing library! 💜
