### ISSUE TITLE
Evision.FlannBasedMatcher.knnMatch incorrect typespecs

### ISSUE THREAD

**Issue by davydog187** [cocoa-xu/evision#242]
I'm getting the following dialyzer error locally

```elixir
The function call will not succeed.

Evision.FlannBasedMatcher.knnMatch(
  _flann :: {:error, binary()} | %Evision.FlannBasedMatcher{:ref => reference()},
  any(),
  any(),
  2
)

breaks the contract
Contract head:
(
  Evision.DescriptorMatcher.t(),
  Evision.Mat.maybe_mat_in(),
  integer(),
  [{atom(), term()}, ...] | nil
) :: [[Evision.DMatch.t()]] | {:error, String.t()}

Contract head:
(
  Evision.DescriptorMatcher.t(),
  Evision.Mat.maybe_mat_in(),
  Evision.Mat.maybe_mat_in(),
  integer()
) :: [[Evision.DMatch.t()]] | {:error, String.t()}

in 1st argument
```

The issue is that `knnMatch/1` expects a `Evision.FlannBasedMatcher.t()`, but the typespec has a `Evisin.DescriptorMatcher.t()`, which is not correct

**Comment by davydog187** [comment]
@cocoa-xu i saw you released 0.2.1. Once you publish it to hex.pm I'll give it a go!

**Comment by cocoa-xu** [comment]
> @cocoa-xu i saw you released 0.2.1. Once you publish it to hex.pm I'll give it a go!

I'll let you know once it's shipped on hex.pm. I'm finishing some last bit with CUDA modules. It should be available later today if not tomorrow! But this won't be a complete fix until #245 is addressed.

**Comment by cocoa-xu** [comment]
v0.2.1 is shipped!

**Comment by davydog187** [comment]
This is now fixed, thanks @cocoa-xu !
