### ISSUE TITLE
Build failure: fatal error: 'evision_consts.h' file not found

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#265]
### Environment

* iMacPro, Intel, Sonoma 14.5
* elixir          1.17.1-otp-27
* erlang          27.0
* Evision 0.2.8, `EVISION_PREFER_PRECOMPILED=false`

### Build tool versions

```bash
% gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

% make --version
GNU Make 3.81
```

I am building from source to be able to use ffmpeg to test out RTSP video streams related to this [elixir forum post](https://elixirforum.com/t/image-an-image-processing-library-based-upon-vix/47568/155)

### Symptoms

* When building from source the build fails with `fatal error: 'evision_consts.h' file not found`
* `find . -name evision_consts.h -print` returns nothing

```bash
.....
-- Build files have been written to: /Users/kip/Development/image/_build/dev/lib/evision/cmake_evision
[ 50%] Building CXX object CMakeFiles/evision.dir/c_src/modules/evision_cuda.cc.o
[ 50%] Building CXX object CMakeFiles/evision.dir/c_src/evision.cpp.o
[ 75%] Building CXX object CMakeFiles/evision.dir/c_src/modules/evision_cuda_ipc.cc.o
In file included from /Users/kip/Development/image/deps/evision/c_src/evision.cpp:38:
In file included from /Users/kip/Development/image/deps/evision/c_src/evision_generated_include.h:2:
/Users/kip/Development/image/deps/evision/c_src/nif_utils.hpp:9:10: fatal error: 'evision_consts.h' file not found
#include "evision_consts.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/evision.dir/c_src/evision.cpp.o] Error 1
make[2]: *** [CMakeFiles/evision.dir/all] Error 2
make[1]: *** [all] Error 2
incomplete build of OpenCV found in '/Users/kip/Development/image/_build/dev/lib/evision/cmake_opencv_4.10.0', please delete that directory and retry
make: *** [/Users/kip/Development/image/_build/dev/lib/evision/priv/evision.so] Error 1
could not compile dependency :evision, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile evision --force", update it with "mix deps.update evision" or clean it with "mix deps.clean evision"
==> image
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

**Comment by cocoa-xu** [comment]
Hi @kipcole9 thanks for reporting this issue, v0.2.9 is on its way. https://github.com/cocoa-xu/evision/commit/e68be6e00b7fe9cf0fc01ae8546dbdc0d874cb1d

**Comment by kipcole9** [comment]
Thank you @cocoa-xu for the quick fix. And yes, I've forgotten to package a required file too so well understood - especially understandable in such a complex lib as this!

**Comment by kipcole9** [comment]
I installed from GitHub directly and everything seems fine (as expected). Just waiting to test the hex release when you get a chance to push it there.

**Comment by cocoa-xu** [comment]
> Thank you @cocoa-xu for the quick fix. And yes, I've forgotten to package a required file too so well understood - especially understandable in such a complex lib as this!

Yeah, this might happen at times 😅. If there's a better way to test it, it'd be great. I'll try to fix this.

But anyway, v0.2.9 is shipped and I hope it has all the necessary files included, if not, please feel free to reopen this one or open another issue, and I'll fix it as soon as possible.

**Comment by kipcole9** [comment]
Thank you very much Cocoa, tested on the hex version and all good.
