### ISSUE TITLE
Evision fails to compile in Livebook

### ISSUE THREAD

**Issue by mlainez** [cocoa-xu/evision#268]
Hi,

I'm trying to use Evision to read a video file with ffmpeg so I added the `{"EVISION_PREFER_PRECOMPILED", "false"}` system env to my Mix.install to make it compile from sources.

However, it fails compilation with the following error:

```
== Compilation error in file lib/generated/evision_.ex ==
** (ArgumentError) invalid module name: {:case, [optimize_boolean: true], [{:fixme!, [line: 1, column: 12], nil}, [do: [{:->, [], [[{:when, [], [{:x, [counter: -576460752303398461], Kernel}, {{:., [], [Kernel, :in]}, [], [{:x, [counter: -576460752303398461], Kernel}, [false, nil]]}]}], true]}, {:->, [], [[{:_, [], Kernel}], false]}]]]}
    (elixir 1.17.2) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

I checked the content of the file in question in `deps/evision/lib/generated/evision_.ex` which starts with the following lines:

```elixir
defmodule !fixme! do
  @type enum :: integer()
  @doc enum: true
  def cv_LOAD_AUTO, do: 0
  ...
``` 

I'm using the following:
OTP27
Elixir 1.17.2
gcc/g++ 11.4.0
livebook v0.14.5

Any idea what I might be missing here ?

Thanks for your help!

**Comment by cocoa-xu** [comment]
Hi @mlainez, thanks for report this. Wondering which version of ffmpeg on your system?

**Comment by mlainez** [comment]
Hi @cocoa-xu, thanks for the swift response. I have ffmpeg 4.4.2 installed.

**Comment by cocoa-xu** [comment]
Hmmm, 4.4.2 should have no issues at all. Could you share which version of evision you're using, and could you upload the full error messages? Many thanks!

**Comment by mlainez** [comment]
Hi @cocoa-xu, here's a gist with the message I can get from livebook: https://gist.github.com/mlainez/ff1e5bc306e08fa3aa070fdad382a56e

It's using Evision 0.2.9
The system I'm getting the error is running Linux Mint

I have another system running Debian12, gcc-12, ffmpeg 5.1.6 and Livebook v0.14.5. On this one I managed to have opencv compile with ffmpeg support through livebook by installing a bunch of dependencies I got from several places online. For the record, there are all the packages I needed to make it work:

`cmake libtbbmalloc2 g++ wget unzip ffmpeg libgtk2.0-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libtbb-dev libjpeg-dev libpng-dev libtiff-dev autoconf automake build-essential cmake git-core libass-dev libfreetype6-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev meson ninja-build pkg-config texinfo wget yasm zlib1g-dev nasm libx264-dev libx265-dev libnuma-dev libvpx-dev libopus-dev libdav1d-dev`

**Comment by cocoa-xu** [comment]
Thanks for the detailed logs @mlainez! A quick solution is to disable the viz module in OpenCV by setting the environment variable `CMAKE_OPENCV_OPTIONS` to `-D WITH_VIZ=OFF` as I haven't ported that module yet. It shouldn't be too hard to do so but I only have some bandwidth at weekends.

**Comment by mlainez** [comment]
Thanks for your help @cocoa-xu. `-D WITH_VIZ=OFF` didn't make any different and it turned out I needed to use `-D WITH_VTK=OFF` instead. Now it's compiling ;)
