### ISSUE TITLE
Help getting the livebook examples to run?

### ISSUE THREAD

**Issue by madasebrof** [cocoa-xu/evision#41]
This library looks very promising!

I was able to get the code to compile locally on my Macbook Air M1 (took a bit of doing, e.g. adding homebrew paths, etc.), but when I try to run the livebooks locally, I am getting this error.

![image](https://user-images.githubusercontent.com/1993403/151381770-e13dfcd1-8488-437d-bbcb-a42c97d3e0e5.png)

The error is obviously not that `make` or `gcc` is missing: 

![image](https://user-images.githubusercontent.com/1993403/151382441-63dcab09-eb3c-433b-8b11-df7217ab0491.png)

I was getting that same error just running a `mix compile` of `evision`, until I fixed my `CPATH` & `LD_LIBRARY_PATH` to include the homebrew paths, e.g. add to `~/.zshrc`:

```
 export LD_LIBRARY_PATH="/opt/homebrew/lib:/opt/homebrew/opt/"
 export CPATH=/opt/homebrew/include
```

I can see that the livebook has the proper paths set, e.g. `System.get_env` from livebook shows:

```
  ...
  "LD_LIBRARY_PATH" => "/opt/homebrew/lib:/opt/homebrew/opt/",
  "CPATH" => "/opt/homebrew/include",
  ...
```

Anyway, just wondering if you are able to run the livebooks & maybe I am missing something obvious!

Thanks again for working on this!!!

**Comment by cocoa-xu** [comment]
I see what might be the reason... I'll document that later but I've pushed a quick fix 5e8d1b5. I tested the new code on my M1 mac with livebook and it works as expected now.

**Comment by cocoa-xu** [comment]
You should be able to install it by re-executing that cell (maybe need to clean the cache? I'm not quite sure if livebook will update the cache or not...)

**Comment by madasebrof** [comment]
Awesome!!! Thanks, will try now!

**Comment by madasebrof** [comment]
Just trying to get livebook to clear cache... it isn't pulling down the new version...

**Comment by cocoa-xu** [comment]
Perhaps `System.cmd("rm", ["-rf", "CACHE_PATH"])`?

CACHE_PATH:
<img width="670" alt="Screenshot 2022-01-27 at 15 37 49" src="https://user-images.githubusercontent.com/89497197/151391678-6f2e6bb9-75c1-4400-bcdb-82c8fbc7aedc.png">

**Comment by cocoa-xu** [comment]
I'm assuming it's now working for you, so I'll close this issue. But if the problem still exists, please feel free to reopen this issue!
