### ISSUE TITLE
`{:ok, ...}` is too verbose`!`

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#43]

**Comment by cocoa-xu** [comment]
Massive thanks to @josevalim for the `Errorize` [demo code](https://gist.github.com/josevalim/7a5ed50ed86a2260d907603ca8223448). Works like a charm!

**Comment by cocoa-xu** [comment]
Notes, for some functions, OpenCV decides to print warnings (tested on OpenCV 4.5.5) instead of reporting error to us, i.e., the NIFs.

For example, for the `imread` function

```elixir
iex(1)> mat = OpenCV.imread!("/path/to/non/exist/image.png")
[ WARN:0@0.008] global /Users/cocoa/Git/evision/3rd_party/opencv/opencv-4.5.5/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/path/to/non/exist/image.png'): can't open/read file: check file path/integrity
iex(2)> mat
nil
```

**Comment by josevalim** [comment]
@cocoa-xu can you configure it to return an error instead? 🤔

**Comment by cocoa-xu** [comment]
This seems to be its intended behaviour, according to their docs

> The function imread loads an image from the specified file and returns it. If the image cannot be
read (because of missing file, improper permissions, unsupported or invalid format), the function
returns an empty matrix ( Mat::data==NULL )

And since everything is immutable in Erlang/Elixir, I think returning a `nil` instead of returning a reference to an empty mat is probably fine?

**Comment by josevalim** [comment]
I see, makes sense. It would be nice if we could return `{:error, "no result"}` in this case but I understand it may be hard to automate this.

**Comment by cocoa-xu** [comment]
In C++, OpenCV returns a valid `cv::Mat` object but everything is `0`.
```cpp
cv::Mat img = cv::imread("/dev/null");
std::cout << img.cols << "\n";
// output: 0
```

In `opencv-python`, the result is `None`

```python
>>> import cv2
>>> mat = cv2.imread("/dev/null")
>>> mat is None
True
```

But sure, I can return an error tuple for this. However, I can only do this for general like when converting from `cv::Mat` to `ERL_NIF_TERM`.

Perhaps we could return `{:error, "empty matrix"}`?

**Comment by josevalim** [comment]
`{:error, "empty matrix"}` love it! Or `{:error, "null matrix"}`. :)
