### ISSUE TITLE
Provide precompiled binaries and auto-generated Elixir source code

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#57]
Using GitHub CI should be okay to achieve this goal. The following operating systems and CPU architectures will be supported.

- macOS, x86_64
- Linux, x86_64
- Linux, arm64

macOS + arm64 could be done (by cross-compiling on an x86_64 macOS), but definitely will need to make changes to the `CMakeLists.txt`. We can compile this natively after arm64 macOS is available to use on GitHub CI.

Of course, there are several things to note:

- We will compile all supported modules in the precompiled version, which means the footprint will be larger (but it should be just ~5-20 megabytes of increment compared to the minimal setup)
- FFmpeg libraries will be needed. Or we can do another version that is not compiled with FFmpeg support.

**Comment by cocoa-xu** [comment]
Works now!

**Comment by cocoa-xu** [comment]
Emulating arm64/armv7 on x86_64 Linux is just way too slow - taking ~3 hours to produce arm64/armv7 precompiled packages. Gotta find a way to cross-compile them with corresponding FFmpeg libraries.

It's pretty easy to install a cross-compiler but I need to install FFmpeg libraries (and their dependencies).

**Comment by zacky1972** [comment]
Great!

**Comment by cocoa-xu** [comment]
Windows precompiled binaries are available now.

**Comment by cocoa-xu** [comment]
Now arm64, armv7l, ppc64le and s390x are all cross-compiled. CI reduced to around 20 minutes.
