### ISSUE TITLE
Guard Preventing Passing "None" For calcHist()

### ISSUE THREAD

**Issue by dbii** [cocoa-xu/evision#74]
In Python, this is allowed:

`cv2.calcHist([image], [0, 1, 2], None, [8, 8, 8],[0, 256, 0, 256, 0, 256])`

When making the equivalent call in evision (I substituted nil for None):

`Cv.calcHist([image], [0, 1, 2], nil, [8, 8, 8],[0, 256, 0, 256, 0, 256])`

the result is ** (FunctionClauseError) no function clause matching in Evision.calcHist/5    **

with the bolded text for **mask** being the issue.

`def calcHist(images, channels, mask, histSize, ranges) when is_list(images) and is_list(channels) and **is_reference(mask)** and is_list(histSize) and is_list(ranges)`

Looking at the OpenCV code, the spec is:

[Python: cv2.calcHist(images, channels, mask, histSize, ranges[, hist[, accumulate]])](https://docs.opencv.org/2.4/modules/imgproc/doc/histograms.html#cv2.calcHist)

where

**mask** – Optional mask. If the matrix is not empty, it must be an 8-bit array of the same size as images[i] .

imgproc.hpp has

`
CV_EXPORTS void calcHist( const Mat* images, int nimages,
                          const int* channels, InputArray mask,
                          OutputArray hist, int dims, const int* histSize,
                          const float** ranges, bool uniform = true, bool accumulate = false );
`

In `hdr_parser.py` the mapping seems to be:

`
if arg_type == "InputArray":
                            arg_type = mat
`
so maybe Python is converting "None" to something automatically? Maybe a blank matrix?

I'm not sure if the solution is to convert nil to blank matrix, or pass in a blank matrix (and maybe make a method to auto-generate it from the image).

I'd be happy to help with this, if I can get some guidance on the best way to go since my knowledge of evision is limited.

**Comment by cocoa-xu** [comment]
Hi @dbii, I think passing in a blank matrix should be okay. It's kind of like the C++ example code in the link you provided (a few lines below).

```
calcHist( &hsv, 1, channels, Mat(), // do not use mask
             hist, 2, histSize, ranges,
             true, // the histogram is uniform
             false );
```

And the equivalent of creating an empty Mat in Evision is `Evision.Mat.empty()`. I'm not using a computer at the moment, hope it works :)
