### ISSUE TITLE
Wrap Evision.Mat as a struct?

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#76]
@cocoa-xu, thanks for this great library. 

I'm just now working on zero-copy integration between [Image](https://github.com/kipcole9/image) and `eVision` (with all the hard work on my side done by @akash-akya).  

I'm wondering if in the future you intend to wrap the NIF reference to an `Evision.Mat` into an Elixir struct?  With the current type being a naked reference its not possible to pattern match on the type and I don't think there is a way to safely identify if the reference is an `Evision.Mat`?

**Comment by cocoa-xu** [comment]
Hi @kipcole9, thanks for bringing this up. I've been thinking about this issue for a while, and what I have in my mind now is that:

The simplest way is perhaps to make the result as a map with two entries (or as a 2-tuple)
- class: a string that indicates the class of the resource, like 'Mat'
- ref: the NIF resource

This will be applied to all functions that return a Mat (or for any result that is a resource).

Then this resulting map/tuple goes to another elixir function and gets wrapped as its corresponding struct in Elixir.

**Comment by kipcole9** [comment]
That sounds great @cocoa-xu - look forward to that whenever you get around to it. I know you're in active development and I expect breaking changes so no issue at all from me!  You'd probably be fine using an atom for the class name given the number of classes is finite and relatively low cardinality. But its largely immaterial to me - its large about pattern matching for my use cases.

**Comment by kipcole9** [comment]
BTW, your packaging pre-built binaries of OpenCV is masterful. I know I wouldn't have the confidence to tackle that myself and its really only when you did that I felt comfortable enough to start diving into the vast world of OpenCV.
