### ISSUE TITLE
Link to the documentation seems broken

### ISSUE THREAD

**Issue by tusqasi** [cocoa-xu/evision#90]
I might have fixed it. If it looks good let me know, I will make a PR.

https://github.com/cocoa-xu/evision/compare/main...tusqasi:evision:main

**Comment by cocoa-xu** [comment]
Hi @tusqasi, thank you very much for reporting this issue! I've updated the link in README.md. 

Also, I plan to release `:evision` on hex.pm soon (this week or by the end of next week), so the documentation will also be available on hex.pm. :)
