### ISSUE TITLE
[Bug] Autocomplete doesn't work.

### ISSUE THREAD

**Issue by tusqasi** [cocoa-xu/evision#98]
I checked with other packages like nx and complex.

I am using neovim with elixir ls. Also tested with vscode elixirls extension. 

I guess that is because of how evision works and compiles from cpp code. 
--- 
In neovim:  
Doesn't Works
![image](https://user-images.githubusercontent.com/24749908/194735232-c7db6f70-11f0-4c41-b3dd-c7bb67b8319c.png)
Works
![image](https://user-images.githubusercontent.com/24749908/194735241-4f36969b-f25d-4920-8bf5-5a5f2d9f392a.png)
![image](https://user-images.githubusercontent.com/24749908/194735356-527bebea-f24a-4ce6-b58b-0fce8106748c.png)

**Comment by kipcole9** [comment]
Autocompletion works correctly in `iex` so it may not be an issue with `eVision` itself.  Have you also filed an issue with `ElixirLS`?

**Comment by tusqasi** [comment]
> Autocompletion works correctly in iex so it may not be an issue with eVision itself.
That might be the case. I raised an issue here first because I thought other packages work fine. You are right iex completions do work.  

I will try the elixirLS.

**Comment by tusqasi** [comment]
yeahhhh... The problem is with ElixirLS. I didn't even check that repo before raising an issue here.😅

I will link it here if someone else come along.
https://github.com/elixir-lsp/elixir-ls/issues/193
